{{- if .Values.web.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-role-graph.fullname" . }}-web-query
  labels:
    component.incloud.io/name: web
    {{- include "k8s-role-graph.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-role-graph.fullname" . }}-web-query
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-role-graph.webServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
