{{- if and .Values.web.enabled .Values.web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-role-graph.webServiceAccountName" . }}
  labels:
    component.incloud.io/name: web
    {{- include "k8s-role-graph.labels" . | nindent 4 }}
  {{- with .Values.web.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.web.serviceAccount.automount }}
{{- end }}
