{{- if .Values.server.enabled }}

{{- $certSecretName := printf "%s-server" (include "k8s-role-graph.fullname" .) -}}
{{- if eq $certSource "secret" }}
{{- $certSecretName = .Values.internalTLS.secret.server.secretName -}}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-role-graph.fullname" . }}-server
  labels:
    component.incloud.io/name: server
    {{- include "k8s-role-graph.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component.incloud.io/name: server
      {{- include "k8s-role-graph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component.incloud.io/name: server
        {{- include "k8s-role-graph.labels" . | nindent 8 }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-role-graph.serverServiceAccountName" . }}
      {{- with .Values.server.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.server.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args:
            - --secure-port={{ .Values.server.service.port }}
            - --tls-cert-file=/certs/tls.crt
            - --tls-private-key-file=/certs/tls.key
          ports:
            - name: https
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          {{- with .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /certs
              name: certificate
            {{- toYaml .Values.server.volumeMounts | nindent 12 }}
      {{- with  }}
      volumes:
        - name: certificate
          secret:
            defaultMode: 420
            secretName: {{ $certSecretName }}
        {{- toYaml .Values.server.volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
