{{- if and .Values.server.enabled .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-role-graph.serverServiceAccountName" . }}
  labels:
    component.incloud.io/name: server
    {{- include "k8s-role-graph.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.server.serviceAccount.automount }}
{{- end }}
