apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.rbacgraph.incloud.io
  annotations:
    cert-manager.io/inject-ca-from: rbac-graph-system/rbacgraph-ca
spec:
  group: rbacgraph.incloud.io
  version: v1alpha1
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: rbacgraph-apiserver
    namespace: rbac-graph-system
    port: 443
  insecureSkipTLSVerify: false
