apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sa.yaml
  - rbac-apiserver.yaml
  - rbac-web.yaml
  - cert-manager.yaml
  - deployment-apiserver.yaml
  - service-apiserver.yaml
  - web.yaml
  - apiservice.yaml
  - pdb.yaml
  - networkpolicy.yaml
