apiVersion: v1
kind: Service
metadata:
  name: rbacgraph-apiserver
  namespace: rbac-graph-system
spec:
  selector:
    app.kubernetes.io/name: rbacgraph-apiserver
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
