apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: rbacgraph-apiserver:dev
    newName: rbacgraph-apiserver
    newTag: dev
  - name: rbacgraph-web:dev
    newName: rbacgraph-web
    newTag: dev

patches:
  - path: resource-limits.yaml
