{{- $intTLS    := .Values.internalTLS -}}
{{- $expose    := .Values.expose -}}

{{- if or (eq $intTLS.certSource "certmanager") (and $expose.enabled (eq $expose.tls.certSource "certmanager")) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "k8s-role-graph.fullname" . }}-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-role-graph.labels" . | nindent 4 }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "k8s-role-graph.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-role-graph.labels" . | nindent 4 }}
spec:
  commonName: {{ include "k8s-role-graph.fullname" . }}-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "k8s-role-graph.fullname" . }}-selfsigned
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: {{ include "k8s-role-graph.fullname" . }}-ca-secret

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "k8s-role-graph.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-role-graph.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "k8s-role-graph.fullname" . }}-ca-secret
{{- end }}
